// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfTFPSDJzAUueeNTbTolOnIiZgscG_mg4',
    appId: '1:388355971444:web:55155488c281ca03cff421',
    messagingSenderId: '388355971444',
    projectId: 'buytopia-90087',
    authDomain: 'buytopia-90087.firebaseapp.com',
    storageBucket: 'buytopia-90087.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUd1DlfBQRZN6-kIB8PaihNECMZGxdX0M',
    appId: '1:388355971444:android:0090f5dcc509db35cff421',
    messagingSenderId: '388355971444',
    projectId: 'buytopia-90087',
    storageBucket: 'buytopia-90087.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqmKEYJczE30P22l_Q5AD2RcVJK-3k6Yc',
    appId: '1:388355971444:ios:1e623b6e5dd66fc1cff421',
    messagingSenderId: '388355971444',
    projectId: 'buytopia-90087',
    storageBucket: 'buytopia-90087.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqmKEYJczE30P22l_Q5AD2RcVJK-3k6Yc',
    appId: '1:388355971444:ios:55189d8686497adfcff421',
    messagingSenderId: '388355971444',
    projectId: 'buytopia-90087',
    storageBucket: 'buytopia-90087.appspot.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
